services:
  - type: web
    name: RajFlaskBlog
    env: python
    pythonVersion: 3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    plan: free
    branch: main
    autoDeploy: true
